### ISSUE TITLE
"Deprecation warning" message using ansible v2.0.1 

### ISSUE THREAD

**Issue by franlr** [davidmnoriega/ansible-role-yum-plugin-priorities#1]
Hi, 
I've tested your role using a CentOS 6.7 + ansible 2.0.1 environment. Everything is fine but I've seen this deprecation warning message:

> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{repositories}}'). 
> This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Are you thinking to adapt the syntax for ansible 2.x?
Thanx!

**Comment by davidmnoriega** [comment]
This has been fix now, v1.1 has been released

**Comment by franlr** [comment]
Well done! Have a great day
